### ISSUE TITLE
Debug build crashed due to sceneData->aggregateInstancePtrs being cleaned up?

### ISSUE THREAD

**Issue by Hearwindsaying** [rohan-sawhney/zombie#1]
Hi Rohan,

When I run demo with `bvc.json`, it crashed at https://github.com/rohan-sawhney/zombie/blob/d1756baf72efbbc568707e8cb584d6914ebbc62f/include/zombie/utils/fcpw_scene_loader.h#L229

It seems that within `fcpw.inl: inline void Scene<DIM>::build(const AggregateType& aggregateType, bool vectorize, bool printStats, bool reduceMemoryFootprint)`, `aggregateInstancePtrs` and `aggregateInstances` will be reset if there is only 1 aggregate instance.

I have yet to dig into the detail of your fcpw/zombie implementation, but my temporary fix for this issue is simply returning `sceneData->aggregate` if `aggregateInstancePtrs` is empty.

Though, release built work magically with disabled indexing check for std::vector under MSVC's implementation and it could fetch the correct aggregate somehow. =D

Best!

**Comment by rohan-sawhney** [comment]
@Hearwindsaying thanks for reporting the bug, fixed now!
