### ISSUE TITLE
Build failure on update to latest version of fcpw

### ISSUE THREAD

**Issue by lakshmipathyarjun6** [rohan-sawhney/zombie#2]
Specifically by this commit in utils/fcpw_scene_loader.h

https://github.com/rohan-sawhney/fcpw/commit/69cf99004fde90adeca01c506e436c6c3e03c581

It's a one character fix of updating Line 26 + updating the dependency - can't directly put up PR from my forked version since it's pointing at my forked fcpw

**Comment by rohan-sawhney** [comment]
Thanks, will fix this soon!
